name: Mise a jour Master Predicts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install requests pandas

      - name: Lancer le script Hacker
        run: python auto_update.py

      - name: Sauvegarder les nouveaux matchs
        run: |
          git config --global user.name 'MasterPredicts-Bot'
          git config --global user.email 'bot@masterpredicts.com'
          git add match.csv
          git commit -m "Mise à jour auto des matchs" || exit 0
          git push

      - name: Notifier sur Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Mise à jour Master Predicts réussie !
            Les nouvelles analyses de foot sont prêtes dans le dépôt.
            Lien : https://github.com/${{ github.repository }}
